{{- if .Values.ingress.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "msfbox.fullname" . }}
  namespace: default
spec:
  routes:
    - services:
      - name: {{ include "msfbox.fullname" . }} 
        port: {{ .Values.service.http.port }}  
    - conditions:
      - prefix: {{ .Values.ingress.path }} 
{{- end }}
