{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ include "msfbox.fullname" . }}
  namespace: default
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "msfbox.fullname" . }} 
            port:
              number: 80
              number: {{ .Values.service.http.port }} 
        path: {{ .Values.ingress.path }}(/|$)(.*)
        pathType: Prefix
{{- end }}
