apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuclei
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/nuclei
    repoURL: https://github.com/heywoodlh/argo-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
