{{- if .Values.nuclei.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-nuclei-cron
spec:
  schedule: "{{ .Values.nuclei.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-nuclei-cron
            image: "{{ .Values.nuclei.image.repository }}:{{ .Values.nuclei.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command:
            - nuclei
            - -config /config/nuclei.conf
            volumeMounts:
            - name: nuclei-conf
              mountPath: /config/nuclei.conf
            {{- if .Values.nuclei.target_list -}}
            - name: nuclei-target-list
              mountPath: /config/target-list.txt
            {{- end }}
          restartPolicy: OnFailure
          volumes:
            - name: nuclei-conf
              configMap:
                name: nuclei-conf
            {{- if .Values.nuclei.target_list -}}
            - name: nuclei-target-list
              configMap:
                name: nuclei-target-list
            {{- end }}
{{- end }}
