{{- if .Values.nuclei.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-nuclei-cron
spec:
  schedule: "{{ .Values.nuclei.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-nuclei-cron
            image: "{{ .Values.nuclei.image.repository }}:{{ .Values.nuclei.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command: [ "nuclei", "-config", "/config/nuclei.conf" ]
            volumeMounts:
              - name: nuclei-conf
                mountPath: /config/
                subPath: nuclei.conf
              - name: nuclei-target-list
                mountPath: /config/
                subPath: target-list.txt
          restartPolicy: OnFailure
          volumes:
            - name: nuclei-conf
              configMap:
                name: nuclei-conf
            - name: nuclei-target-list
              configMap:
                name: nuclei-target-list
{{- end }}
